# -*- coding: utf-8 -*-
import json
import re
import sys

# Replace entries 237-241 in build_chunk_020.py
with open('build_chunk_020.py', 'r', encoding='utf-8') as f:
    content = f.read()

p237_en = '''    # 237
    "Consuming <color=#f26c1c>1 pt</color> of Conduction Index can actively use this skill: select an unoccupied tile around <color=#3487e0>{0}</color> or a target possessing <color=#3487e0>{2}</color> <color=#f26c1c>within a 2-tile radius</color>, land on that tile, and gain <color=#3487e0>{3}</color>. Can be used up to <color=#f26c1c>3 times</color> per turn.\\nAt battle start, inflict on the nearest <color=#f26c1c>10</color> non-boss enemy units field-wide <color=#3487e0>{4}</color> for <color=#f26c1c>1 round</color>, and inflict on the nearest <color=#f26c1c>1</color> non-boss mechanical enemy unit <color=#3487e0>{2}</color>. Self becomes immune to damage and fixed damage until this effect finishes casting.\\nAt battle start, self gains <color=#3487e0>{1}</color>. For every <color=#f26c1c>1</color> allied Doll on field possessing <color=#3487e0>{1}</color> or Corrosive allied Doll without <color=#3487e0>{1}</color>, self damage dealt increases by <color=#f26c1c>16%</color>, up to a maximum of <color=#f26c1c>80%</color>; for every <color=#f26c1c>1</color> allied Doll on field possessing <color=#3487e0>{1}</color>, all allied Dolls possessing <color=#3487e0>{1}</color> gain <color=#f26c1c>1 stack</color> of <color=#3487e0>{5}</color>. At round end, gain <color=#f26c1c>3 pts</color> of Conduction Index.\\nBefore using Active Skill <color=#3487e0>Crimson Projection</color> or Ultimate Skill <color=#3487e0>Domain Cleansing</color>, or upon ending action: if <color=#f26c1c>within an 8-tile radius</color> of self there exists <color=#3487e0>{0}</color>, self gains <color=#f26c1c>1 stack</color> of <color=#3487e0>{6}</color>, triggering up to <color=#f26c1c>1 time</color> per round.\\nIf <color=#f26c1c>within an 8-tile radius</color> of self an enemy target deals damage to an allied unit, execute <color=#3487e0>{7}</color>, dealing to it and all enemy targets <color=#f26c1c>within a 2-tile radius</color> around it cover-ignoring area <color=#f26c1c>80%</color> Attack of <color=#2caadb>Corrosion Damage</color> and <color=#f26c1c>2 pts</color> of Stability Damage; if the target is not within <color=#3487e0>{0}</color>'s <color=#f26c1c>surrounding 8-tile radius</color>, then <color=#3487e0>{0}</color> will not execute <color=#3487e0>{7}</color>, triggering up to <color=#f26c1c>1 time</color> per round.\\nBefore using Active Skill <color=#3487e0>Crimson Projection</color> and Ultimate Skill <color=#3487e0>Domain Cleansing</color>, around self and <color=#3487e0>{0}</color> <color=#f26c1c>within a 4-tile radius</color>, generate <color=#3487e0>{8}</color> tiles for <color=#f26c1c>2 turns</color>.\\nFor each <color=#f26c1c>1 stack</color> of <color=#3487e0>{9}</color> gained, self Crit DMG increases by <color=#f26c1c>4%</color>, up to a maximum of <color=#f26c1c>40%</color>.",'''

p238_en = '''    # 238
    "Consuming <color=#f26c1c>1 pt</color> of Conduction Index can actively use this skill: select an unoccupied tile around <color=#3487e0>{0}</color> or a target possessing <color=#3487e0>{2}</color> <color=#f26c1c>within a 2-tile radius</color>, land on that tile, and gain <color=#3487e0>{3}</color>. Can be used up to <color=#f26c1c>3 times</color> per turn.\\nAt battle start, inflict on the nearest <color=#f26c1c>5</color> non-boss enemy units field-wide <color=#3487e0>{4}</color> for <color=#f26c1c>1 round</color>, and inflict on the nearest <color=#f26c1c>1</color> non-boss mechanical enemy unit <color=#3487e0>{2}</color>. Self becomes immune to damage and fixed damage until this effect finishes casting.\\nAt battle start, self gains <color=#3487e0>{1}</color>. For every <color=#f26c1c>1</color> allied Doll on field possessing <color=#3487e0>{1}</color> or Corrosive allied Doll without <color=#3487e0>{1}</color>, self damage dealt increases by <color=#f26c1c>16%</color>, up to a maximum of <color=#f26c1c>80%</color>; for every <color=#f26c1c>1</color> allied Doll on field possessing <color=#3487e0>{1}</color>, all allied Dolls possessing <color=#3487e0>{1}</color> gain <color=#f26c1c>1 stack</color> of <color=#3487e0>{5}</color>. At round end, gain <color=#f26c1c>3 pts</color> of Conduction Index.\\nBefore using Active Skill <color=#3487e0>Crimson Projection</color> or Ultimate Skill <color=#3487e0>Domain Cleansing</color>, or upon ending action: if <color=#f26c1c>within an 8-tile radius</color> of self there exists <color=#3487e0>{0}</color>, self gains <color=#f26c1c>1 stack</color> of <color=#3487e0>{6}</color>, triggering up to <color=#f26c1c>1 time</color> per round.\\nIf <color=#f26c1c>within an 8-tile radius</color> of self an enemy target deals damage to an allied unit, execute <color=#3487e0>{7}</color>, dealing to it and all enemy targets <color=#f26c1c>within a 2-tile radius</color> around it cover-ignoring area <color=#f26c1c>80%</color> Attack of <color=#2caadb>Corrosion Damage</color> and <color=#f26c1c>2 pts</color> of Stability Damage; if the target is not within <color=#3487e0>{0}</color>'s <color=#f26c1c>surrounding 8-tile radius</color>, then <color=#3487e0>{0}</color> will not execute <color=#3487e0>{7}</color>, triggering up to <color=#f26c1c>1 time</color> per round.\\nBefore using Active Skill <color=#3487e0>Crimson Projection</color> and Ultimate Skill <color=#3487e0>Domain Cleansing</color>, around self and <color=#3487e0>{0}</color> <color=#f26c1c>within a 4-tile radius</color>, generate <color=#3487e0>{8}</color> tiles for <color=#f26c1c>2 turns</color>.\\nFor each <color=#f26c1c>1 stack</color> of <color=#3487e0>{9}</color> gained, self Crit DMG increases by <color=#f26c1c>4%</color>, up to a maximum of <color=#f26c1c>40%</color>.",'''

p239_en = '''    # 239
    "Consuming Conduction Index can actively use this skill: select an unoccupied tile around <color=#3487e0>{0}</color> or a target possessing <color=#3487e0>{2}</color> <color=#f26c1c>within a 2-tile radius</color>, land on that tile, and gain <color=#3487e0>{3}</color>.\\nAt battle start, inflict on the nearest <color=#f26c1c>10</color> non-boss enemy units field-wide <color=#3487e0>{4}</color>, and inflict on the nearest <color=#f26c1c>1</color> non-boss mechanical enemy unit <color=#3487e0>{2}</color>. Self becomes immune to damage and fixed damage until this effect finishes casting.\\nAt battle start, self gains <color=#3487e0>{1}</color>. Based on the number of allied Dolls on field possessing <color=#3487e0>{1}</color> or Corrosive allied Dolls without <color=#3487e0>{1}</color>, self damage dealt increases; based on the number of allied Dolls on field possessing <color=#3487e0>{1}</color>, all allied Dolls possessing <color=#3487e0>{1}</color> gain <color=#3487e0>{5}</color>. At round end, gain Conduction Index.\\nBefore using Active Skill <color=#3487e0>Crimson Projection</color> or Ultimate Skill <color=#3487e0>Domain Cleansing</color>, or upon ending action: if <color=#f26c1c>within an 8-tile radius</color> of self there exists <color=#3487e0>{0}</color>, self gains <color=#3487e0>{6}</color>.\\nIf <color=#f26c1c>within an 8-tile radius</color> of self an enemy target deals damage to an allied unit, execute <color=#3487e0>{7}</color>, dealing to it and all enemy targets <color=#f26c1c>within a 2-tile radius</color> around it cover-ignoring area <color=#2caadb>Corrosion Damage</color> and Stability Damage; if the target is not within <color=#3487e0>{0}</color>'s <color=#f26c1c>surrounding 8-tile radius</color>, then <color=#3487e0>{0}</color> will not execute <color=#3487e0>{7}</color>.\\nBefore using Active Skill <color=#3487e0>Crimson Projection</color> and Ultimate Skill <color=#3487e0>Domain Cleansing</color>, around self and <color=#3487e0>{0}</color> <color=#f26c1c>within a 4-tile radius</color>, generate <color=#3487e0>{8}</color> tiles.\\nBased on stacks of <color=#3487e0>{9}</color> gained, self Crit DMG increases.",'''

p240_en = '''    # 240
    "Consuming Conduction Index can actively use this skill: select an unoccupied tile around <color=#3487e0>{0}</color> or a target possessing <color=#3487e0>{2}</color> <color=#f26c1c>within a 2-tile radius</color>, land on that tile, and gain <color=#3487e0>{3}</color>.\\nAt battle start, inflict on the nearest <color=#f26c1c>10</color> non-boss enemy units field-wide <color=#3487e0>{4}</color>, and inflict on the nearest <color=#f26c1c>1</color> non-boss mechanical enemy unit <color=#3487e0>{2}</color>. Self becomes immune to damage and fixed damage until this effect finishes casting.\\nAt battle start, self gains <color=#3487e0>{1}</color>. Based on the number of allied Dolls on field possessing <color=#3487e0>{1}</color> or Corrosive allied Dolls without <color=#3487e0>{1}</color>, self damage dealt increases; based on the number of allied Dolls on field possessing <color=#3487e0>{1}</color>, all allied Dolls possessing <color=#3487e0>{1}</color> gain <color=#3487e0>{5}</color>. At round end, gain Conduction Index.\\nBefore using Active Skill <color=#3487e0>Crimson Projection</color> or Ultimate Skill <color=#3487e0>Domain Cleansing</color>, or upon ending action: if <color=#f26c1c>within an 8-tile radius</color> of self there exists <color=#3487e0>{0}</color>, self gains <color=#3487e0>{6}</color>.\\nIf <color=#f26c1c>within an 8-tile radius</color> of self an enemy target deals damage to an allied unit, execute <color=#3487e0>{7}</color>, dealing to it and all enemy targets <color=#f26c1c>within a 2-tile radius</color> around it cover-ignoring area <color=#2caadb>Corrosion Damage</color> and Stability Damage; if the target is not within <color=#3487e0>{0}</color>'s <color=#f26c1c>surrounding 8-tile radius</color>, then <color=#3487e0>{0}</color> will not execute <color=#3487e0>{7}</color>.\\nBefore using Active Skill <color=#3487e0>Crimson Projection</color> and Ultimate Skill <color=#3487e0>Domain Cleansing</color>, around self and <color=#3487e0>{0}</color> <color=#f26c1c>within a 4-tile radius</color>, generate <color=#3487e0>{8}</color> tiles,\\nBased on stacks of <color=#3487e0>{9}</color> gained, self Crit DMG increases.",'''

p241_en = '''    # 241
    "Consuming Conduction Index can actively use this skill: select an unoccupied tile around <color=#3487e0>{0}</color> or a target possessing <color=#3487e0>{2}</color> <color=#f26c1c>within a 2-tile radius</color>, land on that tile, and gain <color=#3487e0>{3}</color>.\\nAt battle start, inflict on the nearest <color=#f26c1c>5</color> non-boss enemy units field-wide <color=#3487e0>{4}</color>, and inflict on the nearest <color=#f26c1c>1</color> non-boss mechanical enemy unit <color=#3487e0>{2}</color>. Self becomes immune to damage and fixed damage until this effect finishes casting.\\nAt battle start, self gains <color=#3487e0>{1}</color>. Based on the number of allied Dolls on field possessing <color=#3487e0>{1}</color> or Corrosive allied Dolls without <color=#3487e0>{1}</color>, self damage dealt increases; based on the number of allied Dolls on field possessing <color=#3487e0>{1}</color>, all allied Dolls possessing <color=#3487e0>{1}</color> gain <color=#3487e0>{5}</color>. At round end, gain Conduction Index.\\nBefore using Active Skill <color=#3487e0>Crimson Projection</color> or Ultimate Skill <color=#3487e0>Domain Cleansing</color>, or upon ending action: if <color=#f26c1c>within an 8-tile radius</color> of self there exists <color=#3487e0>{0}</color>, self gains <color=#3487e0>{6}</color>.\\nIf <color=#f26c1c>within an 8-tile radius</color> of self an enemy target deals damage to an allied unit, execute <color=#3487e0>{7}</color>, dealing to it and all enemy targets <color=#f26c1c>within a 2-tile radius</color> around it cover-ignoring area <color=#2caadb>Corrosion Damage</color> and Stability Damage; if the target is not within <color=#3487e0>{0}</color>'s <color=#f26c1c>surrounding 8-tile radius</color>, then <color=#3487e0>{0}</color> will not execute <color=#3487e0>{7}</color>.\\nBefore using Active Skill <color=#3487e0>Crimson Projection</color> and Ultimate Skill <color=#3487e0>Domain Cleansing</color>, around self and <color=#3487e0>{0}</color> <color=#f26c1c>within a 4-tile radius</color>, generate <color=#3487e0>{8}</color> tiles.\\nBased on stacks of <color=#3487e0>{9}</color> gained, self Crit DMG increases.",'''

# Find the start of # 237 and end of # 241
pattern = r'    # 237\n.*?(?=    # 242\n)'
replacement = f"{p237_en}\n{p238_en}\n{p239_en}\n{p240_en}\n{p241_en}\n"

new_content = re.sub(pattern, replacement, content, flags=re.DOTALL)
with open('build_chunk_020.py', 'w', encoding='utf-8') as f:
    f.write(new_content)

print("Updated build_chunk_020.py")
