# -*- coding: utf-8 -*-
part5 = {
    "{0}  <color=#595c5d>待修复</color>": "{0}  <color=#595c5d>To Be Repaired</color>",
    "——███！抓住我！！": "—███! Grab onto me!!",
    "——不是，不是这样……就算你这么说，我也不能背叛母亲……": "—No, that's not it... Even if you say that, I cannot betray Mother...",
    "——你……": "—You...",
    "——你，你这个……麻烦的孩子。": "—You... you troublesome child.",
    "——加快速度。": "—Pick up the pace.",
    "——原来如此。": "—I see.",
    "——可，可你们呢！": "—B-But what about you all?!",
    "——吉利！太吉利了！指挥官保佑啊啊啊！": "—Lucky! That's so lucky! Bless the Commander, ahhh!",
    "——呀！": "—Ah!",
    "——呵呵，如果指挥官在的话，或许也会这样回答你吧？": "—Hehe, if the Commander were here, maybe that's how they'd answer you too?",
    "——啧！看起来，战场的流向确实转变了呢。": "—Tsk! It seems the flow of the battlefield truly has shifted.",
    "——啧，走吧。": "—Tsk, let's go.",
    "——嗯？真是聪明得让人讶异啊，O-201。": "—Hm? You're astonishingly clever, O-201.",
    "——嘀。": "—Beep.",
    "——噤声。": "—Quiet.",
    "——够了！": "—Enough!",
    "——她们，真是指挥官的人形！": "—They really are the Commander's Dolls!",
    "——如果我持续思考这件事，就会变得很不对劲。而我越控制自己不去思考，就会越频繁地将这段无法删除的回忆捡起。": "—If I keep dwelling on this, something starts to feel very wrong. And the harder I try not to think about it, the more frequently this undeletable memory resurfaces.",
    "——必定有什么事情，在持续地困扰您。": "—There must be something that continues to trouble you.",
    "——快清醒一下，我们没多少时间了。": "—Snap out of it, quickly. We don't have much time.",
    "——我的同伴，她们怎么样了！？": "—My companions, how are they doing?!",
    "——所以，你不可能具有与我相同的力量，你只是用了某种方法，窃取了我所感知到的未来。": "—Therefore, it's impossible for you to possess the same power as me. You merely used some method to steal the future I perceived.",
    "——接下来，我会认真振作起来的！": "—From now on, I will pull myself together and do my best!",
    "——星渊？": "—Astral Abyss?",
    "——架子！一定是膨胀的架子害了你啊！": "—Putting on airs! It was definitely putting on airs that ruined you!",
    "——气……": "—Grr...",
    "——没错，铁血从来只信服主人的命令，主人不在，铁血绝不会服从旁人。": "—That's right. Sangvis only ever obeys Master's orders. In Master's absence, Sangvis will never submit to anyone else.",
    "——直到我出现？": "—Until I appeared?",
    "——看起来，的确不能对铁血人形掉以轻心。": "—It seems one truly cannot let their guard down around Sangvis Dolls.",
    "——看，只要使用小苏打溶剂，就能很轻松地去除顽固的油渍哦。还有这种灰尘一定要用湿布来擦，像这样……": "—See, with a baking soda solution, you can easily remove stubborn grease stains. And this kind of dust must be wiped with a damp cloth, like this...",
    "——等到那时候，就算是妈妈，也护不住你了。": "—When that time comes, not even Mother will be able to protect you.",
    "——网络出现波动，需要进行相关处理。": "—Network fluctuations detected. Appropriate action required.",
    "——诶？该不会只给充电吧？难道要我们自己点外卖吗？真是的，我要对上头抱怨！": "—Eh? Don't tell me they only provide charging? Are we supposed to order takeout ourselves? Honestly, I'm going to complain to the higher-ups!",
    "——请您原谅，我的胆大妄为。": "—Please forgive my presumption.",
    "——长官？": "—Commander?",
    "——首先容我总述。": "—First, allow me to provide a summary."
}
