# -*- coding: utf-8 -*-
part4 = {
    "<size=26>留，下，他。</size>": "<size=26>Leave. Him. Here.</size>",
    "<size=30>兰汀长官——！</size>": "<size=30>Commander Lentine—!</size>",
    "<size=30>听我说！</size>": "<size=30>Listen to me!</size>",
    "<size=30>大家，卧倒！</size>": "<size=30>Everyone, get down!</size>",
    "<size=30>开啊！听我的命令啊！</size>": "<size=30>Fire! Obey my command!</size>",
    "<size=30>我操这什么？！暴露了？？？</size>": "<size=30>What the fuck is this?! We're compromised???</size>",
    "<size=30>我操！我和你拼了！</size>": "<size=30>Fuck! I'll take you down with me!</size>",
    "<size=30>所谓“拖延一小会儿”是他妈以秒计数的吗！</size>": "<size=30>Is your damn \"buying a little time\" counted in fucking seconds?!</size>",
    "<size=30>拿下他！</size>": "<size=30>Take him down!</size>",
    "<size=30>是炸弹，卧倒！</size>": "<size=30>It's a bomb, get down!</size>",
    "<size=30>涅托！</size>": "<size=30>Nyto!</size>",
    "<size=30>这群，该死的，地鼠！</size>": "<size=30>These damn moles!</size>",
    "<size=30>长官，长官？！</size>": "<size=30>Commander, Commander?!</size>",
    "<傀儡人形·暴风猎手三型>造成的伤害提升100%，稳态崩溃时移除": "Damage dealt by <Neobrute - Stormhunter Type 3> is increased by 100%, removed upon Stability Break",
    "<傀儡人形·暴风猎手三型>造成的伤害提升25%，稳态崩溃时移除": "Damage dealt by <Neobrute - Stormhunter Type 3> is increased by 25%, removed upon Stability Break",
    "<傀儡人形·暴风猎手三型>造成的伤害提升50%，稳态崩溃时移除": "Damage dealt by <Neobrute - Stormhunter Type 3> is increased by 50%, removed upon Stability Break",
    "<傀儡人形·暴风猎手三型>造成的伤害提升，稳态崩溃时移除": "Damage dealt by <Neobrute - Stormhunter Type 3> is increased, removed upon Stability Break",
    "<震荡泰坦>的技能<泰坦威势>替换为技能<不屈泰坦>，并使自身基础生命值，攻击力，防御力提升100%。（仅第二战场生效）": "<Temblor Titan>'s skill <Titan's Might> is replaced with <Unyielding Titan>, and increases own base HP, Attack, and Defense by 100%. (Takes effect in the second battlefield only)",
    "<震荡泰坦>的技能<泰坦威势>替换为技能<不屈泰坦>，并使自身基础生命值，攻击力，防御力提升100%（仅第二战场生效）": "<Temblor Titan>'s skill <Titan's Might> is replaced with <Unyielding Titan>, and increases own base HP, Attack, and Defense by 100% (Takes effect in the second battlefield only)",
    "BOSS，你这是在进行巧克力的非法收购吗？不用解释，理由我知道……毕竟我也是来给你送巧克力的。这是我用执行正义的决心亲手制作的，请务必尝尝看。": "Boss, are you running an illicit chocolate acquisition operation? No need to explain, I know why... after all, I'm here to give you chocolate too. I made this with my own hands, infused with my determination to execute justice. Please, you must try it.",
    "BOSS，元旦快乐。根据安全条例，即使是新年，安防工作也不能松懈。不过……如果你愿意陪我一起的话，这条路线刚好会经过餐厅。怎么样，要顺便一起吃顿跨年晚餐吗？": "Boss, Happy New Year. According to security regulations, security duty cannot be relaxed even for New Year's Day. But... if you're willing to come along with me, this patrol route happens to pass by the cafeteria. How about it? Care to have a New Year's Eve dinner together on the way?",
    "BOSS，如果有空的话，能帮我把这些礼物带给孤儿院的孩子们吗？我这边有巡逻任务，一时抽不开身……嗯，如果是交给BOSS的话，我就放心了。当然，里面也有一份是给你的。": "Boss, if you have time, could you help me deliver these gifts to the children at the orphanage? I'm on patrol duty and can't step away right now... Mm, if I'm entrusting them to you, Boss, I can rest easy. Of course, there's a gift in there for you too.",
    "BOSS，生日快乐。为了买到这份符合你气质的礼物，我这个月的赤字已经提前到来了——不过没关系，能庆祝你生日的机会只有今天。请拆开看看吧。": "Boss, Happy Birthday. To buy a gift that truly suits you, my deficit for this month has arrived ahead of schedule—but that's fine. Today is the only chance I get to celebrate your birthday. Please open it and have a look.",
    "Darling，快来这边！看！这是我特意准备的线香烟花，留着等你来一起放呢。我听说，如果和喜欢的人一起点燃线香烟花能看到不同的颜色……我们快点来试试吧！": "Darling, come over here! Look! I specifically prepared these sparklers so we could light them together when you got here. I heard that if you light sparklers with someone you love, you can see different colors... Let's hurry and try it!",
    "M16可比她们还强哦。": "M16 is even stronger than them, you know.",
    "M16在一次任务里感染了铁血的病毒，之后失踪，成为了铁血的一员与我们为敌；不过就算这样，她也没有忘记自己是AR小队的一员，最后还是成功回归了格里芬。": "During a mission, M16 was infected by the Sangvis virus and subsequently went missing, becoming a member of Sangvis Ferri and fighting against us. Even so, she never forgot that she was a member of the AR Team, and in the end, she successfully returned to Griffin.",
    "O-201大人的精神尚不稳定，彼此之间又有链接，对外界的刺激本就格外敏感。": "Lady O-201's mental state is still unstable, and with their mutual neural link, she is inherently hypersensitive to external stimuli.",
    "O-201大人，跟我们来。": "Lady O-201, come with us.",
    "O-201已从精神世界唤醒。": "O-201 has been awakened from the mental realm.",
    "O-201的初始天赋优于其他所有实验体。": "O-201's initial aptitude surpasses all other test subjects.",
    "O-201的数据我已经检查过。": "I have already checked O-201's data.",
    "OKOK~断罪者，开启最大输出功率——！！": "OK, OK~ Sinbreaker, initiate maximum power output—!!",
    "OTs-14，不必紧张，我来帮她吧。": "OTs-14, no need to be nervous. Allow me to help her.",
    "RPK-16一代": "RPK-16 Gen 1",
    "Surprise！！！超超超超世界级美少女到访——": "Surprise!!! A super-super-super-super world-class gorgeous girl has arrived—",
    "xx系统": "xx System",
    "z主线1": "z Main 1",
    "z主线2": "z Main 2",
    "z主线3": "z Main 3",
    "z主线4": "z Main 4",
    "z主线5": "z Main 5",
    "z主线6": "z Main 6",
    "z主线7": "z Main 7",
    "z主线8": "z Main 8",
    "z主线9": "z Main 9",
    "z挑战1": "z Challenge 1",
    "z挑战2": "z Challenge 2",
    "z挑战3": "z Challenge 3",
    "z挑战4": "z Challenge 4",
    "z挑战5": "z Challenge 5",
    "z支线1": "z Side 1",
    "z支线2": "z Side 2",
    "z支线3": "z Side 3",
    "z支线4": "z Side 4",
    "z支线5": "z Side 5",
    "z支线6": "z Side 6",
    "z物资1": "z Supply 1",
    "z物资2": "z Supply 2",
    "z物资3": "z Supply 3",
    "z物资4": "z Supply 4",
    "z物资5": "z Supply 5"
}
