# -*- coding: utf-8 -*-
part2 = {
    "<color=#f6de73>{}：</color>还真是有趣的度假体验。": "<color=#f6de73>{}：</color>This really is an enjoyable vacation experience.",
    "<color=#f6de73>{}：</color>还请你保密啊……": "<color=#f6de73>{}：</color>Please keep this a secret, okay...?",
    "<color=#f6de73>{}：</color>这片海域真漂亮啊……是黄区看不到的风景呢。": "<color=#f6de73>{}：</color>This stretch of ocean is so beautiful... A view you could never see in the Yellow Zone.",
    "<color=#f6de73>春田：</color>不过这个颜色还差一笔。": "<color=#f6de73>Springfield: </color>Though this color still needs one more brushstroke.",
    "<color=#f6de73>春田：</color>呀啊……没想到指挥官会这样恶作剧……那我就……": "<color=#f6de73>Springfield: </color>Ah... I didn't expect the Commander to tease me like this... In that case, I'll...",
    "<color=#f6de73>春田：</color>呀啊！": "<color=#f6de73>Springfield: </color>Ah!",
    "<color=#f6de73>春田：</color>呵呵呵呵，那么轮到我了哦。": "<color=#f6de73>Springfield: </color>Hehehe, then it's my turn.",
    "<color=#f6de73>春田：</color>呵呵呵，刚刚指挥官的投喂要是被其他人知道了，感觉艾莫号又会掀起一阵风波哦。": "<color=#f6de73>Springfield: </color>Hehehe, if the others found out the Commander just fed me, I feel like it'd cause quite a stir back on the Elmo.",
    "<color=#f6de73>春田：</color>呵呵呵，看来这些海鸥十分亲近人呢。": "<color=#f6de73>Springfield: </color>Hehehe, it seems these seagulls are quite fond of people.",
    "<color=#f6de73>春田：</color>呵呵呵，这里的风景确实宜人。": "<color=#f6de73>Springfield: </color>Hehehe, the scenery here truly is delightful.",
    "<color=#f6de73>春田：</color>哈哈哈哈，能看到您如此开心的表情，这两瓶香槟也值得了。": "<color=#f6de73>Springfield: </color>Hahaha, seeing you look so happy makes these two bottles of champagne well worth it.",
    "<color=#f6de73>春田：</color>哎呀……您这是……呵呵呵。": "<color=#f6de73>Springfield: </color>Oh my... You're... hehehe.",
    "<color=#f6de73>春田：</color>哎呀，不好！": "<color=#f6de73>Springfield: </color>Oh no!",
    "<color=#f6de73>春田：</color>哎呀，您现在的表情，真有趣。": "<color=#f6de73>Springfield: </color>My, the expression on your face right now is priceless.",
    "<color=#f6de73>春田：</color>哎呀，是不是又知道了我不为人知的一面呢？": "<color=#f6de73>Springfield: </color>My, did you just discover another side of me you hadn't seen before?",
    "<color=#f6de73>春田：</color>哦？您想继续刚刚的牌局吗？要是输了的话可是有惩罚游戏的哦。": "<color=#f6de73>Springfield: </color>Oh? Would you like to continue our card game from earlier? If you lose, there will be a penalty game, you know.",
    "<color=#f6de73>春田：</color>啊……": "<color=#f6de73>Springfield: </color>Ah...",
    "<color=#f6de73>春田：</color>噗……哈哈哈哈哈哈，您还是赶紧坐下来休息吧。": "<color=#f6de73>Springfield: </color>Pfft... Hahahaha, you'd better hurry and sit down to rest.",
    "<color=#f6de73>春田：</color>噗……没想到您会这么配合啊。": "<color=#f6de73>Springfield: </color>Pfft... I didn't expect you to be so cooperative.",
    "<color=#f6de73>春田：</color>噗，指挥官您的表情真的很有趣~": "<color=#f6de73>Springfield: </color>Pfft, Commander, your expression is truly amusing~",
    "<color=#f6de73>春田：</color>在这里哦~": "<color=#f6de73>Springfield: </color>Over here~",
    "<color=#f6de73>春田：</color>希望以后，我也能有像这样，独占您的时间。": "<color=#f6de73>Springfield: </color>I hope that in the future, I'll also have moments like this where I can have you all to myself.",
    "<color=#f6de73>春田：</color>您可一定要猜对噢~": "<color=#f6de73>Springfield: </color>You simply must guess right~",
    "<color=#f6de73>春田：</color>您是想要再小憩一会儿，还是继续我们刚刚的游戏呢？": "<color=#f6de73>Springfield: </color>Would you like to take another little nap, or continue our game from earlier?",
    "<color=#f6de73>春田：</color>您真是温柔呢……": "<color=#f6de73>Springfield: </color>You truly are gentle...",
    "<color=#f6de73>春田：</color>您能够喜欢，那我购买这艘帆船也值得了。": "<color=#f6de73>Springfield: </color>If you like it, then buying this sailboat was well worth it.",
    "<color=#f6de73>春田：</color>我这一次带来了帕拉达嘉的新鲜小番茄哦。经过冰镇后，一定很好吃。": "<color=#f6de73>Springfield: </color>I brought fresh cherry tomatoes from Paradajz this time. Chilled on ice, they're sure to be delicious.",
    "<color=#f6de73>春田：</color>指、指挥官？！": "<color=#f6de73>Springfield: </color>C-Commander?!",
    "<color=#f6de73>春田：</color>指挥官~": "<color=#f6de73>Springfield: </color>Commander~",
    "<color=#f6de73>春田：</color>指挥官要不要也试试看。": "<color=#f6de73>Springfield: </color>Would you like to try it too, Commander?",
    "<color=#f6de73>春田：</color>指挥官，不如我们做些什么来庆祝这次度假？": "<color=#f6de73>Springfield: </color>Commander, why don't we do something to celebrate this vacation?",
    "<color=#f6de73>春田：</color>指挥官，您没事吧！": "<color=#f6de73>Springfield: </color>Commander, are you alright?!",
    "<color=#f6de73>春田：</color>指挥官，您醒了。呵呵呵，难得看到您如此放松的表情。": "<color=#f6de73>Springfield: </color>Commander, you're awake. Hehehe, it's rare to see you look so relaxed.",
    "<color=#f6de73>春田：</color>指挥官，抱歉！您没事吧？！": "<color=#f6de73>Springfield: </color>Commander, I'm sorry! Are you alright?!",
    "<color=#f6de73>春田：</color>接下来是期待已久的惩罚游戏了~": "<color=#f6de73>Springfield: </color>Next up is the long-awaited penalty game~",
    "<color=#f6de73>春田：</color>既然如此，就让我来为您再调制一杯酒吧。": "<color=#f6de73>Springfield: </color>In that case, allow me to mix another drink for you.",
    "<color=#f6de73>春田：</color>有的时候我更希望能在您身边做一个充满童趣的人形呢。": "<color=#f6de73>Springfield: </color>Sometimes, I wish I could just be a playful, childlike Doll by your side.",
    "<color=#f6de73>春田：</color>来指挥官，啊~~~~~~~": "<color=#f6de73>Springfield: </color>Here, Commander, say ahh~~~~~~~",
    "<color=#f6de73>春田：</color>欸！": "<color=#f6de73>Springfield: </color>Eh!",
    "<color=#f6de73>春田：</color>没关系，只要您没有从我身边跑掉就好。": "<color=#f6de73>Springfield: </color>It's alright, as long as you didn't run away from me.",
    "<color=#f6de73>春田：</color>能和您一起度过假期，真是太幸运了。": "<color=#f6de73>Springfield: </color>I'm truly lucky to be able to spend this vacation with you.",
    "<color=#f6de73>春田：</color>虽然只剩下一点点……但还是让我们一起干杯吧。": "<color=#f6de73>Springfield: </color>Though there's only a little bit left... let's still have a toast together.",
    "<color=#f6de73>春田：</color>诶？指挥官，那样摇的话……": "<color=#f6de73>Springfield: </color>Eh? Commander, if you shake it like that...",
    "<color=#f6de73>春田：</color>这是我们刚刚一起上色的海螺，颜料已经干掉了啊。": "<color=#f6de73>Springfield: </color>This is the conch shell we painted together earlier. The paint has already dried.",
    "<color=#f6de73>春田：</color>这是我的心意，希望指挥官能够永远保持笑容，幸福安宁。": "<color=#f6de73>Springfield: </color>This is a token of my feelings. I hope you will always keep your smile, Commander, and find happiness and peace.",
    "<color=#f6de73>春田：</color>这杯可是我的推荐特调哦。": "<color=#f6de73>Springfield: </color>This drink is my specially recommended mix.",
    "<color=#f6de73>春田：</color>那就先让我再多占有一下这份体验吧。": "<color=#f6de73>Springfield: </color>Then allow me to cherish and monopolize this experience just a little longer.",
    "<color=#f6de73>春田：</color>香槟？": "<color=#f6de73>Springfield: </color>Champagne?"
}
