# -*- coding: utf-8 -*-
part1 = {
    "(她干脆地俯下身，以极近的距离静静凝视。)": "(She leans down briskly, gazing quietly at me from mere inches away.)",
    "(我尽力调整着呼吸。可那份温和而恰到好处的揉捏，还有她不时贴近的脸庞，似乎都使这件事情变得越发困难了。)": "(I try my best to steady my breathing. But her gentle, perfectly measured kneading, along with her face drawing close from time to time, only seem to make it all the more difficult.)",
    "(眼前骤然一暗，温热的气息扑面而来，停在我的颊边。）": "(Darkness suddenly falls before my eyes as a warm breath washes over me, coming to rest beside my cheek.)",
    "(终于，在持续协助我调整呼吸无果后，代理人停下了手。)": "(At last, after her continued attempts to help me steady my breathing prove fruitless, Agent pauses her hands.)",
    "(随即，柔软的手指落到我的胸口和肩膀，代理人悉心地将精油抹上我的皮肤，淡淡的香味与湿润感漫开，温热的手指再度落下，以轻柔的力度揉捏起那些僵硬的肌肉。)": "(Then, soft fingers settle upon my chest and shoulders. Agent meticulously applies essential oil to my skin; a subtle fragrance and moisture spread across it, and her warm fingers descend once more, kneading my stiff muscles with gentle care.)",
    "(随着揉捏，代理人也不时俯身凑近，似是仔细观察着按摩效果，她垂下的发丝飘拂着，与那双专注的眼眸一起吸引住我的视线。)": "(As she kneads, Agent leans in close from time to time, seemingly observing the effects of the massage. Her hanging locks of hair sway gently, capturing my gaze together with those focused eyes.)",
    "001……阁下。": "001... Your Excellency.",
    "20层呢？或者18层？我们可以从其他楼层爬过去。": "What about the 20th floor? Or the 18th? We can climb across from another floor.",
    "24分解锁": "Unlocked at 24 pts",
    "72架无人机有超过半数被击毁，园区共发生了138起爆破事件，损失还在计算中——至于信标，有一台脱离了我们的控制范围，前往莫科什去了。": "Over half of the 72 drones were destroyed, and a total of 138 explosions occurred within the park. Losses are still being calculated—as for the beacons, one of them broke out of our range of control and headed toward Mokosh.",
    "<color=#0074FF>……你接受得还挺快的。</color>": "<color=#0074FF>...You accepted that pretty quickly.</color>",
    "<color=#0074FF>佐伊，莫科什内部现在失去了所有联系艾莫号的通讯手段，我们需要信标来恢复通信。</color>": "<color=#0074FF>Zoe, Mokosh has lost all means of contacting the Elmo right now. We need the beacon to restore communications.</color>",
    "<color=#0074FF>佐伊，那个指挥官邮箱是假的，你发的邮件和照片都被贝丝蒂拦截了，她在我们人形的平台上说你要和她斗还早三十年。</color>": "<color=#0074FF>Zoe, that Commander email address is fake. The emails and photos you sent were intercepted by Besti. She said on our Doll network that you're thirty years too early to challenge her.</color>",
    "<color=#0074FF>你好，佐伊，我们受艾莫号的委托而来。</color>": "<color=#0074FF>Hello, Zoe. We've come on behalf of the Elmo.</color>",
    "<color=#0074FF>多谢，帮大忙了，佐伊。</color>": "<color=#0074FF>Thanks, that's a huge help, Zoe.</color>",
    "<color=#0074FF>我们不在现场，具体情况不太清楚。不过据我所知，她们奋战到了最后一刻，现在或许依旧在奋战，这也是我们代替她们过来的原因。</color>": "<color=#0074FF>We weren't on site, so we don't know the exact situation. But as far as I know, they fought until the very last moment, and may still be fighting right now. That's why we're here in their stead.</color>",
    "<color=#0074FF>我们尽量吧——你也要忍耐哦，好了，通讯时间要到了，请藏好这个扫地机器人。</color>": "<color=#0074FF>We'll do our best—hang in there, okay? Alright, our communication time is almost up. Please hide this sweeping robot.</color>",
    "<color=#0074FF>我们是波波沙、纳甘、科谢尼娅和莫辛纳甘，贝丝蒂和芙铃没有提起我们吗？</color>": "<color=#0074FF>We're PPSh-41, Nagant, Ksenia, and Mosin-Nagant. Didn't Besti and Fulin mention us?</color>",
    "<color=#0074FF>我叫波波沙……</color>": "<color=#0074FF>My name is PPSh-41...</color>",
    "<color=#160d0d>重逢礼遇</color>": "<color=#160d0d>Reunion Privileges</color>",
    "<color=#160d0d>重逢诗篇</color>": "<color=#160d0d>Reunion Poems</color>",
    "<color=#2c2829>未完成</color>": "<color=#2c2829>Incomplete</color>",
    "<color=#3487e0>{0}</color>专属标记。不可驱散。": "<color=#3487e0>{0}</color> exclusive mark. Cannot be dispelled.",
    "<color=#3487e0>{0}</color>效果提升，伤害系数提高至<color=#f26c1c>2000+45%</color>出力参数。\n对P.M.C.的机械类怪物成的伤害提高<color=#f26c1c>100%</color>。": "<color=#3487e0>{0}</color> effect enhanced: Damage multiplier is increased to <color=#f26c1c>2000+45%</color> of Power Value.\nDamage dealt to P.M.C. mechanical enemies is increased by <color=#f26c1c>100%</color>.",
    "<color=#3487e0>{0}</color>效果提升，伤害系数提高至<color=#f26c1c>2000+45%</color>阵列强度。\n对P.M.C.的机械类怪物成的伤害提高<color=#f26c1c>100%</color>。": "<color=#3487e0>{0}</color> effect enhanced: Damage multiplier is increased to <color=#f26c1c>2000+45%</color> of HOC Power.\nDamage dealt to P.M.C. mechanical enemies is increased by <color=#f26c1c>100%</color>.",
    "<color=#3487e0>{0}</color>效果提升，受到的<color=#2caadb>浊刻伤害</color>和近战伤害提高至<color=#3487e0>{0}</color>层数×<color=#f26c1c>12%</color>。普通单位受到的固定伤害提高至<color=#3487e0>{0}</color>层数×<color=#f26c1c>12%</color>×自身最大生命值。": "<color=#3487e0>{0}</color> effect enhanced: <color=#2caadb>Hydro damage</color> and melee damage taken are increased to <color=#3487e0>{0}</color> stacks × <color=#f26c1c>12%</color>. Fixed damage taken by normal units is increased to <color=#3487e0>{0}</color> stacks × <color=#f26c1c>12%</color> × max HP.",
    "<color=#3487e0>{0}</color>数量上限提高至<color=#f26c1c>2个</color>。\n被动新增效果：战斗开始时，获得<color=#f26c1c>3点</color>导染指数。": "Maximum quantity of <color=#3487e0>{0}</color> increased to <color=#f26c1c>2</color>.\nPassive New Effect: At the start of battle, gain <color=#f26c1c>3 points</color> of Index.",
    "<color=#3487e0>{0}</color>的效果改为造成的伤害降低<color=#f26c1c>40%</color>，持续<color=#f26c1c>3个大回合</color>。": "The effect of <color=#3487e0>{0}</color> is changed to: Damage dealt is reduced by <color=#f26c1c>40%</color> for <color=#f26c1c>3 rounds</color>.",
    "<color=#3487e0>{0}</color>首次达到<color=#f26c1c>100层</color>时，驱散<color=#f26c1c>50层</color>该效果。每场战斗至多触发<color=#f26c1c>1次</color>。": "When <color=#3487e0>{0}</color> reaches <color=#f26c1c>100 stacks</color> for the first time, dispels <color=#f26c1c>50 stacks</color> of this effect. Can trigger up to <color=#f26c1c>1 time</color> per battle.",
    "<color=#3487e0>{1}</color>首次处于<color=#3487e0>{2}</color>状态时，清空主动技能<color=#3487e0>决胜千里</color>的冷却时间，每场战斗至多触发<color=#f26c1c>1次</color>。\n自身和<color=#3487e0>{1}</color>的最大生命值提高<color=#f26c1c>15%</color>，当前大回合<color=#3487e0>{1}</color>每进行<color=#f26c1c>1次</color>攻击，下个大回合自身和<color=#3487e0>{1}</color>造成的浊刻伤害提高<color=#f26c1c>20%</color>。\n刘莳在场时，自身和所有友方实体召唤物获得<color=#3487e0>{0}</color>。": "When <color=#3487e0>{1}</color> enters the <color=#3487e0>{2}</color> state for the first time, resets the cooldown of the active skill <color=#3487e0>Cavalier's Leap</color>. Can trigger up to <color=#f26c1c>1 time</color> per battle.\nIncreases max HP of self and <color=#3487e0>{1}</color> by <color=#f26c1c>15%</color>. For every <color=#f26c1c>1</color> attack <color=#3487e0>{1}</color> makes during the current round, Hydro damage dealt by self and <color=#3487e0>{1}</color> in the next round is increased by <color=#f26c1c>20%</color>.\nWhen Liushih is on the field, self and all allied physical summons gain <color=#3487e0>{0}</color>.",
    "<color=#3487e0>{4}</color>持续时间增加<color=#f26c1c>1个</color>大回合，场上至多存在<color=#f26c1c>3个</color>该召唤物。<color=#3487e0>{4}</color>继承的初始属性提升到<color=#f26c1c>100%</color>。<color=#3487e0>{4}</color>效果新增，<color=#3487e0>{4}</color>出生时对<color=#f26c1c>周围半径6格内</color>的所有友方单位施加<color=#f26c1c>1层</color><color=#3487e0>{5}</color>。": "The duration of <color=#3487e0>{4}</color> is increased by <color=#f26c1c>1</color> round, with up to <color=#f26c1c>3</color> of this summon allowed on the field simultaneously. The initial stats inherited by <color=#3487e0>{4}</color> are increased to <color=#f26c1c>100%</color>. <color=#3487e0>{4}</color> gains a new effect: When <color=#3487e0>{4}</color> is summoned, to all allied units <color=#f26c1c>within a 6-tile radius</color>, applies <color=#f26c1c>1 stack</color> of <color=#3487e0>{5}</color>.",
    "<color=#3487e0>{6}</color>效果提升，攻击力提高，提高量为自身<color=#f26c1c>3%</color>初始攻击力。": "<color=#3487e0>{6}</color> effect enhanced: Attack is increased by <color=#f26c1c>3%</color> of own initial Attack.",
    "<color=#ca3745>代理人、针</color>等新人形登场，解锁全新战役剧情": "New Dolls such as <color=#ca3745>Agent and Igla</color> arrive! Unlock brand-new campaign storylines",
    "<color=#d8c7a9>完成{0}个任务共可获得</color>": "<color=#d8c7a9>Complete {0} missions to obtain a total of</color>",
    "<color=#df9e00ff>【衣装·睡醒的人鱼】</color>与特殊部件<color=#df9e00ff>【爱尔辛·烈日晴空】</color>均为独立奖品，需分别获取": "<color=#df9e00ff>[Outfit: The Waking Mermaid]</color> and special part <color=#df9e00ff>[Elsin: Blazing Sun]</color> are independent rewards and must be acquired separately",
    "<color=#efefef>{0}后结束</color>": "<color=#efefef>Ends in {0}</color>",
    "<color=#efefef>任务进度</color>": "<color=#efefef>Mission Progress</color>",
    "<color=#efefef>已完成</color>": "<color=#efefef>Completed</color>",
    "<color=#efefef>重逢许可×70</color>": "<color=#efefef>Reunion Permit ×70</color>",
    "<color=#f26c1c>数值提升：</color>不再使用普攻，基础技能系数提高<color=#f26c1c>60%</color>。": "<color=#f26c1c>Stat Boost: </color>No longer uses basic attacks; base skill multiplier is increased by <color=#f26c1c>60%</color>.",
    "<color=#f26c1c>数值提升：</color>持有护盾的目标受到的伤害降低<color=#f26c1c>40%</color>。": "<color=#f26c1c>Stat Boost: </color>Damage taken by targets with shields is reduced by <color=#f26c1c>40%</color>.",
    "<color=#f26c1c>数值提升：</color>持有护盾的目标暴击伤害提高<color=#f26c1c>60%</color>。": "<color=#f26c1c>Stat Boost: </color>Crit DMG of targets with shields is increased by <color=#f26c1c>60%</color>.",
    "<color=#f6de73>{}：</color>可惜，鱼跑了。不过难得看到春田你窘迫的模样，也是很有趣。": "<color=#f6de73>{}：</color>What a pity, the fish got away. But seeing you flustered like that for once, Springfield, was quite amusing.",
    "<color=#f6de73>{}：</color>呃啊……": "<color=#f6de73>{}：</color>Ugh...",
    "<color=#f6de73>{}：</color>嗯？": "<color=#f6de73>{}：</color>Hm?",
    "<color=#f6de73>{}：</color>春田你不来一颗吗？": "<color=#f6de73>{}：</color>Won't you have one too, Springfield?",
    "<color=#f6de73>{}：</color>春田，鱼竿是不是有动静？": "<color=#f6de73>{}：</color>Springfield, did the fishing rod just twitch?",
    "<color=#f6de73>{}：</color>本地居民也太不地道了，这不是抢劫吗？": "<color=#f6de73>{}：</color>The locals here are unbelievable. Isn't that just robbery?",
    "<color=#f6de73>{}：</color>没想到春田你会喜欢这么童趣的玩法。": "<color=#f6de73>{}：</color>I never expected you to enjoy something so childlike, Springfield.",
    "<color=#f6de73>{}：</color>真是漂亮啊。": "<color=#f6de73>{}：</color>It's truly beautiful."
}
